Add path – itemSearch
rarible/union-openapi pull request #110
Opened 2022-07-15 06:43 UTC by iskurenkov

Add path – itemSearch:
1. Decided to leave tokenId, I understand that it is not in Solana, so that something can be found in Solana, you just need to skip it.
2. I did not add metaWidth/metaHight/metaSize to the metaContent object for searching. It seems to be redundant for the first stage.
3. Using the Sale object, you can find items on sale

In Item:
1. Removed pending, because we abandoned them and remove them.
2. Removed contract, because it is not in Solana.For all other blockchains, it is possible to use the attribute - collection.

2022-07-19 08:09 UTC, evgenynacu commented on openapi.yaml
> +  /v1/items/search:
can we use just /v1/items ?

2022-07-19 08:09 UTC, evgenynacu commented on openapi.yaml
> +        - name: "cursor"
we previously talked about naming this like "nextPage" or something like this

2022-07-19 08:14 UTC, evgenynacu commented on openapi.yaml
> +        collection:
should be multiple

2022-07-19 08:15 UTC, evgenynacu commented on openapi.yaml
> +        blockchain:
should be multiple?

2022-07-19 08:15 UTC, evgenynacu commented on openapi.yaml
> +        tokenId:
do we need to filter out by token id? What's the use case?

2022-07-19 08:15 UTC, evgenynacu commented on openapi.yaml
> +        creator:
should be multiple?

2022-07-19 08:16 UTC, evgenynacu commented on openapi.yaml
> +        lazySupply:
I don't think we need to filter by lazy supply

2022-07-19 08:16 UTC, evgenynacu commented on openapi.yaml
> +        meta:
Here is the same as for collections: full text search should have one field

2022-07-22 10:52 UTC, iskurenkov commented on openapi.yaml
> +  /v1/items/search:
Yes of course, I did it in this [commit](https://github.com/rarible/union-openapi/pull/110/commits/1b2ab0292de6ab8943b47c4e70942369b6ac4fdf)

2022-07-22 10:53 UTC, iskurenkov commented on openapi.yaml
> +        - name: "cursor"
It's true, I did it in this [commit](https://github.com/rarible/union-openapi/commit/9b2436a526d2f35248115a7ddf0bef733a6863b5)

2022-07-22 10:53 UTC, iskurenkov commented on openapi.yaml
> +        collection:
I think so, since I, as a user, will be able to search for items with the parameters I need only in the collections I need

2022-07-22 10:53 UTC, iskurenkov commented on openapi.yaml
> +        blockchain:
I think so, since I, as a user, will be able to search for items by name (fullTextSearch) only in the blockchains that interest me

2022-07-22 10:53 UTC, iskurenkov commented on openapi.yaml
> +        tokenId:
Since NFT is also affected by its tokenid, I decided to add the ability to specify this parameter in the search. For example, we can say for sure that a BAYC with ID: 6 is more expensive than one with ID: 9598. Although the second item has a much higher rarityScore, I think this is due to its tokenId.

[link to BAYC on RarityScore with confirmation](https://raritysniper.com/bored-ape-yacht-club?sort=nftId:asc&buyItNow=true)

2022-07-22 10:53 UTC, iskurenkov commented on openapi.yaml
> +        creator:
Changed the scheme, probably if we had modifiers, then it would be relevant to leave multiple. For example, one could find items where the owner is 0x1.. or 0x2..

2022-07-22 10:53 UTC, iskurenkov commented on openapi.yaml
> +        lazySupply:
As a user, I would like to be able to control this setting. For example, if I specify 0, then I exclude all lazyItems from the search results, or if I specify more than 4 in lazy and more than 1 in supply, I can find 1155 items that are lazy and that someone bought, potentially interesting items to buy.

2022-07-22 10:53 UTC, iskurenkov commented on openapi.yaml
> +        meta:
Left one field for searching by name and description. Added a search field for traists like a market, but without the range parameter, since users will not understand how to use it.

2022-08-04 12:32 UTC, evgenynacu requested changes

2022-08-04 12:32 UTC, evgenynacu commented on openapi.yaml
> +  /v1/items/:
should be /v1/items, without one more /

2022-08-04 12:32 UTC, evgenynacu commented on openapi.yaml
> +        blockchain:
need to be named "blockchains" then

2022-08-04 12:32 UTC, evgenynacu commented on openapi.yaml
> +        collection:
need to be named "collections" then?

2022-08-04 12:32 UTC, evgenynacu commented on openapi.yaml
> +        metaContent:
Let's remove this "metaContent" for now. Probably we won't allow search for this from the start. It's not a common use case and more es storage is needed for it

2022-08-04 12:32 UTC, evgenynacu commented on openapi.yaml
> +            priceUsd:
We need to groom this. Probably, we need to allow to specify currency to allow searching for ETH > 0.1 ETH for example

2022-08-05 07:03 UTC, iskurenkov commented on openapi.yaml
> +  /v1/items/:
Fixed

2022-08-05 07:03 UTC, iskurenkov commented on openapi.yaml
> +        metaContent:
Removed

2022-08-05 07:03 UTC, iskurenkov commented on openapi.yaml
> +            priceUsd:
Suggested a solution

2022-08-10 08:31 UTC, merged