[api-v1-collection] add new fullTextSearch
rarible/union-openapi pull request #111
Opened 2022-07-15 10:58 UTC by iskurenkov

1. Changed searchCollections path, removed /search from path 
2. Changed full test search in collections

2022-07-19 07:51 UTC, evgenynacu commented on openapi.yaml
> +  /v1/collections/:
it should not end with slash

2022-07-19 08:02 UTC, evgenynacu requested changes

2022-07-21 11:58 UTC, iskurenkov commented on openapi.yaml
> +  /v1/collections/:
Fixed.

2022-07-21 11:58 UTC, iskurenkov commented on openapi.yaml
> +          default: null
Judging by the specification, the "default" parameter for the Schema Object is optional. Removed.

2022-08-05 09:26 UTC, evgenynacu requested changes

2022-08-05 11:39 UTC, iskurenkov commented on openapi.yaml
> +  /v1/collections:
Испправил

2022-08-09 12:39 UTC, evgenynacu requested changes

2022-08-09 12:39 UTC, evgenynacu commented on openapi.yaml
> +        blockchain:
blockchains

2022-08-09 12:39 UTC, evgenynacu commented on openapi.yaml
> +        type:
types

2022-08-09 12:39 UTC, evgenynacu commented on openapi.yaml
> +        owner:
owners

2022-08-10 08:54 UTC, iskurenkov commented on openapi.yaml
> +        blockchain:
Fixed

2022-08-10 08:54 UTC, iskurenkov commented on openapi.yaml
> +        type:
Fixed

2022-08-10 08:54 UTC, iskurenkov commented on openapi.yaml
> +        owner:
Fixed

2022-08-10 09:09 UTC, merged