ALPHA-496 get activities by multiple collections
rarible/union-openapi pull request #87
Opened 2022-05-24 14:06 UTC by atapin

2022-05-24 14:29 UTC, zolt reviewed
I think, we need to add new parameter for collections list for backward compatibility (if it is planned to be released in 1.27)

2022-05-25 09:27 UTC, augur requested changes
Consider retargetting this PR to 1.27 branch, as master now has 1.28  (if it is planned to be released in 1.27)

2022-05-27 10:49 UTC, atapin commented on openapi.yaml
> +              $ref: "#/components/schemas/ContractAddress"
no, discussed with @evgenynacu

2022-06-02 06:04 UTC, augur approved these changes

2022-06-02 07:02 UTC, closed without merging